export interface Quote {
  text: string
  author: string
}

export const LEADERSHIP_QUOTES: Quote[] = [
  { text: 'Führung ist die Fähigkeit, Visionen in Realität zu verwandeln.', author: 'Warren Bennis' },
  { text: 'Wer führen will, muss zuerst sich selbst führen können.', author: 'Erasmus von Rotterdam' },
  { text: 'Management ist, die Dinge richtig zu machen; Führung ist, die richtigen Dinge zu tun.', author: 'Peter Drucker' },
  { text: 'Die Aufgabe eines Führers ist es, seine Leute von dort, wo sie sind, dorthin zu bringen, wo sie noch nicht gewesen sind.', author: 'Henry Kissinger' },
  { text: 'Wenn deine Handlungen andere dazu inspirieren, mehr zu träumen, mehr zu lernen, mehr zu tun und mehr zu werden, dann bist du eine Führungspersönlichkeit.', author: 'John Quincy Adams' },
  { text: 'Innovation unterscheidet zwischen einem Anführer und einem Nachfolger.', author: 'Steve Jobs' },
  { text: 'Ein Anführer ist ein Händler in Hoffnung.', author: 'Napoleon Bonaparte' },
  { text: 'Führung ist keine Position oder ein Titel, es ist Handeln und Beispiel.', author: 'Donald McGannon' },
  { text: 'Wer keine Vision hat, vermag weder große Hoffnung zu erfüllen, noch große Vorhaben zu verwirklichen.', author: 'Thomas Woodrow Wilson' },
  { text: 'Die beste Art, die Zukunft vorherzusagen, ist, sie zu erschaffen.', author: 'Peter Drucker' },
  { text: 'Ein großer Anführer ist nicht unbedingt derjenige, der die größten Dinge tut. Er ist derjenige, der die Menschen dazu bringt, die größten Dinge zu tun.', author: 'Ronald Reagan' },
  { text: 'Führung bedeutet nicht, die Kontrolle über andere zu haben. Es bedeutet, andere zu befähigen, die Kontrolle über sich selbst zu übernehmen.', author: 'Unbekannt' },
  { text: 'Bevor du eine Führungspersönlichkeit bist, geht es bei Erfolg darum, dich selbst weiterzuentwickeln. Wenn du eine Führungspersönlichkeit bist, geht es bei Erfolg darum, andere weiterzuentwickeln.', author: 'Jack Welch' },
  { text: 'Man führt Menschen nicht, indem man sie auf den Kopf schlägt – das ist Körperverletzung, nicht Führung.', author: 'Dwight D. Eisenhower' },
  { text: 'Echte Führung bedeutet, die Verantwortung für den Erfolg der anderen zu übernehmen.', author: 'Simon Sinek' },
  { text: 'Um die Menschen zu führen, gehe hinter ihnen.', author: 'Laotse' },
  { text: 'Führung ist ein Dienst am Menschen, keine Herrschaft über Menschen.', author: 'Hans-Dietrich Genscher' },
  { text: 'Man gewinnt nicht, wenn man keine guten Spieler hat, aber man kann mit guten Spielern verlieren, wenn man nicht richtig führt.', author: 'Lou Holtz' },
  { text: 'Die wichtigste Zutat für gute Führung ist Vertrauen.', author: 'Unbekannt' },
  { text: 'Ein Führer ist am besten, wenn die Leute kaum wissen, dass er existiert. Wenn seine Arbeit getan ist, werden sie sagen: Wir haben es selbst getan.', author: 'Laotse' },
  { text: 'Integrität ist die wertvollste Eigenschaft einer Führungspersönlichkeit.', author: 'Brian Tracy' },
  { text: 'Führung erfordert Mut, denn man muss oft als Erster Neuland betreten.', author: 'Unbekannt' },
  { text: 'Charakter ist wichtiger als Intelligenz für eine Führungskraft.', author: 'Warren Buffett' },
  { text: 'Man kann nicht führen, indem man mit dem Finger auf jemanden zeigt. Man führt, indem man dorthin geht, wo man andere haben möchte.', author: 'Ken Kesey' },
  { text: 'Ein Leader ist jemand, der den Weg kennt, den Weg geht und den Weg zeigt.', author: 'John C. Maxwell' },
  { text: 'Das Beispiel ist nicht das wichtigste Mittel, um andere zu beeinflussen. Es ist das einzige.', author: 'Albert Schweitzer' },
  { text: 'Wer führen will, muss dienen können.', author: 'Deutsches Sprichwort' },
  { text: 'Führung bedeutet, die Verantwortung zu übernehmen, auch wenn man nicht schuld ist.', author: 'Unbekannt' },
  { text: 'Die Kunst der Führung besteht darin, „Nein" zu sagen, nicht „Ja". Es ist sehr einfach, „Ja" zu sagen.', author: 'Tony Blair' },
  { text: 'Allein können wir so wenig tun; gemeinsam können wir so viel tun.', author: 'Helen Keller' },
  { text: 'Umgeben Sie sich mit den besten Leuten, delegieren Sie Autorität und mischen Sie sich nicht ein.', author: 'Ronald Reagan' },
  { text: 'Keiner von uns ist so klug wie wir alle zusammen.', author: 'Ken Blanchard' },
  { text: 'Die besten Führungskräfte sind jene, die sich selbst überflüssig machen.', author: 'Unbekannt' },
  { text: 'Einen guten Führer erkennt man daran, dass er die Talente seiner Mitarbeiter besser nutzt als diese selbst.', author: 'Unbekannt' },
  { text: 'Wenn du schnell gehen willst, geh alleine. Wenn du weit gehen willst, geh mit anderen.', author: 'Afrikanisches Sprichwort' },
  { text: 'Gute Führung bedeutet, durchschnittliche Menschen dazu zu bringen, überdurchschnittliche Arbeit zu leisten.', author: 'John D. Rockefeller' },
  { text: 'Vertrauen ist das Schmiermittel, das es Organisationen ermöglicht, zu funktionieren.', author: 'Warren Bennis' },
  { text: 'Delegieren heißt nicht, Aufgaben loszuwerden, sondern Verantwortung zu teilen.', author: 'Unbekannt' },
  { text: 'Wer Angst hat, dass sein Team ihn übertrifft, wird nie ein großer Leader sein.', author: 'Unbekannt' },
  { text: 'In ruhiger See kann jeder das Steuer halten.', author: 'Publilius Syrus' },
  { text: 'Ein Pessimist sieht die Schwierigkeit in jeder Chance; ein Optimist sieht die Chance in jeder Schwierigkeit.', author: 'Winston Churchill' },
  { text: 'Führung ist die Kunst, Menschen dazu zu bringen, das zu tun, was sie nicht tun wollen, um das zu erreichen, was sie erreichen wollen.', author: 'Harry S. Truman' },
  { text: 'Die einzige Konstante in der Führung ist der Wandel.', author: 'Unbekannt' },
  { text: 'Krisen meistern ist die Reifeprüfung jeder Führungskraft.', author: 'Unbekannt' },
  { text: 'Wer aufhört, besser zu werden, hat aufgehört, gut zu sein.', author: 'Philip Rosenthal' },
  { text: 'Mut steht am Anfang des Handelns, Glück am Ende.', author: 'Demokrit' },
  { text: 'Erfolg ist nicht endgültig, Misserfolg ist nicht fatal: Es ist der Mut weiterzumachen, der zählt.', author: 'Winston Churchill' },
  { text: 'Die gefährlichste Phrase in der Führung ist: „Das haben wir schon immer so gemacht."', author: 'Grace Hopper' },
  { text: 'Das größte Problem in der Kommunikation ist die Illusion, sie hätte stattgefunden.', author: 'George Bernard Shaw' },
  { text: 'Ein guter Führer hört mehr zu, als er spricht.', author: 'Unbekannt' },
  { text: 'Wer Fragen stellt, der führt.', author: 'Konrad Adenauer' },
  { text: 'Feedback ist das Frühstück für Champions.', author: 'Ken Blanchard' },
  { text: 'Ehrlichkeit ohne Mitgefühl ist Grausamkeit; Mitgefühl ohne Ehrlichkeit ist Manipulation.', author: 'Unbekannt' },
  { text: 'Die Sprache der Führung ist die Sprache der Wertschätzung.', author: 'Unbekannt' },
  { text: 'Man kann nicht nicht kommunizieren.', author: 'Paul Watzlawick' },
  { text: 'Ein Wort des Lobes zur rechten Zeit ist wie ein Funke in der Dunkelheit.', author: 'Unbekannt' },
  { text: 'Wer andere überzeugen will, muss selbst überzeugt sein.', author: 'Isokrates' },
  { text: 'Klarheit ist die wichtigste Eigenschaft einer Führungskraft.', author: 'Marcus Buckingham' },
  { text: 'Fast alle Menschen können die Widrigkeiten des Lebens ertragen. Wenn du den Charakter eines Menschen testen willst, gib ihm Macht.', author: 'Abraham Lincoln' },
  { text: 'Führung ist keine Lizenz zum Gängeln, sondern eine Verantwortung für den Schutz anderer.', author: 'Simon Sinek' },
  { text: 'Wer sich selbst nicht beherrscht, kann auch andere nicht führen.', author: 'Konfuzius' },
  { text: 'Der Preis der Größe heißt Verantwortung.', author: 'Winston Churchill' },
  { text: 'Demut ist das Fundament wahrer Größe.', author: 'Unbekannt' },
  { text: 'Ego ist der Feind jeder guten Führung.', author: 'Ryan Holiday' },
  { text: 'Führung ist ein Privileg, das man sich jeden Tag neu verdienen muss.', author: 'Unbekannt' },
  { text: 'Niemand ist so groß, dass er nicht von anderen lernen könnte.', author: 'Unbekannt' },
  { text: 'Verantwortung kann man nicht teilen. Entweder man hat sie, oder man hat sie nicht.', author: 'Unbekannt' },
  { text: 'Ich stelle Leute ein, die klüger sind als ich, und dann gehe ich ihnen aus dem Weg.', author: 'Lee Iacocca' },
  { text: 'Menschen sind nicht dein wichtigstes Kapital. Die richtigen Menschen sind es.', author: 'Jim Collins' },
  { text: 'Führe die Menschen so, wie sie sein könnten, und du hilfst ihnen, das zu werden, was sie sein sollten.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Micromanagement ist das Eingeständnis eigener Unsicherheit.', author: 'Unbekannt' },
  { text: 'Wer seine Mitarbeiter klein hält, wird nie ein großes Unternehmen führen.', author: 'Unbekannt' },
  { text: 'Gute Führungskräfte schaffen Raum für Fehler, aber keinen Raum für Faulheit.', author: 'Unbekannt' },
  { text: 'Das Ziel von Führung ist nicht, mehr Follower zu haben, sondern mehr Führer zu produzieren.', author: 'Ralph Nader' },
  { text: 'Vertrauen ist gut, Zutrauen ist besser.', author: 'Unbekannt' },
  { text: 'Ein Coach hilft dir, deine eigene Lösung zu finden; ein Boss diktiert sie dir.', author: 'Unbekannt' },
  { text: 'Gute Führung beginnt mit dem Glauben an das Potenzial des Gegenübers.', author: 'Unbekannt' },
  { text: 'Wer zwei Hasen gleichzeitig jagt, wird keinen fangen.', author: 'Konfuzius' },
  { text: 'Strategie ohne Taktik ist der langsamste Weg zum Sieg. Taktik ohne Strategie ist der Lärm vor der Niederlage.', author: 'Sunzi' },
  { text: 'Nicht entscheiden ist auch eine Entscheidung – meist die schlechteste.', author: 'Unbekannt' },
  { text: 'Führung bedeutet, im Sturm die Richtung vorzugeben, auch wenn man selbst nass wird.', author: 'Unbekannt' },
  { text: 'Konzentration ist das Geheimnis der Stärke.', author: 'Ralph Waldo Emerson' },
  { text: 'Man kann ein Team nicht führen, wenn man kein Ziel hat, das größer ist als man selbst.', author: 'Unbekannt' },
  { text: 'Disziplin ist die Brücke zwischen Zielen und Erfolg.', author: 'Jim Rohn' },
  { text: 'Warte nicht auf den perfekten Moment, nimm den Moment und mach ihn perfekt.', author: 'Unbekannt' },
  { text: 'Ein Plan ist nichts, Planung ist alles.', author: 'Dwight D. Eisenhower' },
  { text: 'Kultur frisst Strategie zum Frühstück.', author: 'Peter Drucker' },
  { text: 'Die Leute werden vergessen, was du gesagt hast, aber sie werden nie vergessen, wie sie sich bei dir gefühlt haben.', author: 'Maya Angelou' },
  { text: 'Führung ist die Kunst, Herzen zu gewinnen, bevor man Köpfe bewegt.', author: 'Unbekannt' },
  { text: 'Niemand kümmert sich darum, wie viel du weißt, bis er weiß, wie viel du dich kümmerst.', author: 'Theodore Roosevelt' },
  { text: 'Wer die Menschen verstehen will, muss ihre Träume kennen.', author: 'Unbekannt' },
  { text: 'Echte Autorität braucht keine laute Stimme.', author: 'Unbekannt' },
  { text: 'Respekt verdient man sich. Ehrlichkeit schenkt man. Vertrauen muss man aufbauen.', author: 'Unbekannt' },
  { text: 'Das Geheimnis der Führung ist einfach: Sei ein Mensch.', author: 'Unbekannt' },
  { text: 'Es ist schwer, jemanden zu führen, der dich nicht respektiert.', author: 'Unbekannt' },
  { text: 'Ein Tyrann braucht Sklaven, ein Führer braucht Partner.', author: 'Unbekannt' },
  { text: 'Ein Zauderer am Steuer ist gefährlicher als ein Draufgänger.', author: 'Unbekannt' },
  { text: 'Ein Unternehmen ist nur so gut wie das Lächeln seiner Mitarbeiter.', author: 'Unbekannt' },
  { text: 'Ein Leader ohne Humor ist wie ein Auto ohne Stoßdämpfer.', author: 'Unbekannt' },
  { text: 'Ein Leader bittet nicht um Erlaubnis, er schafft Tatsachen.', author: 'Unbekannt' },
]

/** Get a deterministic-ish quote for today (changes daily) */
export function getTodaysQuote(): Quote {
  const today = new Date()
  const dayIndex = today.getFullYear() * 366 + today.getMonth() * 31 + today.getDate()
  return LEADERSHIP_QUOTES[dayIndex % LEADERSHIP_QUOTES.length]
}
